components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

        grpc-blocking-task-processor:
            worker_threads: $worker-grpc-threads
            thread_name: grpc-worker
    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        watch-synchronization:
        etcd-service:
        revision-service:
        kv-service:
        query-optimizer:
        batch-processor:
            write-delay: 20
        grpc-server:
            port: 8081
            service-defaults:
                task-processor: main-task-processor

        grpc-server-middlewares-pipeline:

        congestion-control:
            fake-mode: true
        grpc-server-logging:
        grpc-server-deadline-propagation:

        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                USERVER_RPS_CCONTROL_ENABLED: false

        testsuite-support: {}

        http-client:
            load-enabled: $is-testing
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        dns-client:
            fs-task-processor: fs-task-processor
        cred-prov:
        watch-service:

        ydb:
            operation-settings:
                retries: 100
                get-session-timeout: 100000
                operation-timeout: 100000
                cancel-after: 100000
                client-timeout: 100000
            credentials-provider: 'cred-prov'


            databases:
                test:
                    endpoint: 127.0.0.1:2136
                    database: /Root/test
                    credentials:
                        #TODO auth
                        enforce_user_token_requirement: false
        default-secdist-provider:
            config: ../configs/secure_data.json